spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wolf4busydb?characterEncoding=UTF-8
    username: wolf4busyuser # 本番は起動引数で与える
    password: wolf4busypass # 本番は起動引数で与える
    driverClassName: com.mysql.jdbc.Driver
  messages:
    basename: messages
    cache-duration: -1
    encoding: UTF-8
server:
  port: 8086
  servlet:
    context-path: /wolf4busy
    session:
      timeout: 86400
logging:
  level:
    org.springframework: DEBUG
    root: INFO
    org.seasar.dbflute: ERROR
  file: /var/log/wolf4busy/zzzzztomcat.log