name: delivery

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  delivery:
    runs-on: [ self-hosted ]
    steps:
      - name: clone repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: download arm64 JDK 21
        run: |
          download_url="https://cdn.azul.com/zulu/bin/zulu21.36.17-ca-jdk21.0.4-linux_aarch64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '21'
          architecture: arm64

      - name: build
        run: |
          ./gradlew jibDockerBuild

      - name: deploy
        run: |
          docker login ghcr.io -u h-orito -p ${{ secrets.PACKAGE_PAT }}
          docker push ghcr.io/h-orito/firewolf

      - name: release
        run: |
          kubectl delete pod -l app=firewolf
